//
// Created by admin on 2018/12/7.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniUtils_FfempegUtils */

#ifndef _Included_jniUtils_FfempegUtils
#define _Included_jniUtils_FfempegUtils

#include <android/log.h>
#include "android_log.h"
#include "ffmpeg.h"

#ifdef __cplusplus


extern "C" {
#endif
/*
 * Class:     jniUtils_FfempegUtils
 * Method:    runFfempeg
 * Signature: ()V
 *
 *logcat  只能输出error 和 info
 */

JNIEnv *jniEnv = NULL;
jobject jobject_global = NULL;
char *time2 = "time=";

void progress(char *line) {
    /*char *p = strstr(line, time2);
    //这里不清楚为什么 释放没有效果 ，所以加了一个判断 返回的字符指针是否包含"time=",减少返回的字符指针
    //不加这个判断是 ，会报内存溢出的异常，但是奇怪的是明明已经释放了内存引用
    if (p != NULL) {
        //输出日志格式
        //   __android_log_print(ANDROID_LOG_DEBUG,"MDL","%s\n",line);
        //获得jclass对象
        jclass jclass_global = (*jniEnv)->FindClass(jniEnv, "jniUtils/FfempegUtils");
        //获得FfempegUtils中的progress方法的 jmethodID
        jmethodID jMethod_progress = (*jniEnv)->GetMethodID(jniEnv, jclass_global, "progress",
                                                            "(Ljava/lang/String;)V");
        //字符指针转换成字符串
        jstring jString1 = (*jniEnv)->NewStringUTF(jniEnv, line);
        //调用FfempegUtils的progress方法
        (*jniEnv)->CallVoidMethod(jniEnv, jobject_global, jMethod_progress,
                                  jString1);
        //释放内存

        //  (*jniEnv)->DeleteLocalRef(jniEnv,jMethod_progress);

        (*jniEnv)->ReleaseStringUTFChars(jniEnv, jString1, line);
        (*jniEnv)->DeleteLocalRef(jniEnv, jString1);
    }
    free(line);*/
}

JNIEXPORT jint JNICALL Java_jniUtils_FfempegUtils_runFfempeg
        (JNIEnv *env, jobject jobject, jobjectArray commands) {
//FFmpeg av_log() callback
    jniEnv = env;
    jobject_global = jobject;

    int argc = (*env)->GetArrayLength(env, commands);
    char *argv[argc];

    int i;
    for (i = 0; i < argc; i++) {
        jstring js = (jstring) (*env)->GetObjectArrayElement(env, commands, i);
        argv[i] = (char *) (*env)->GetStringUTFChars(env, js, 0);
    }
    int result = runFfempeg(argc, argv);
    //释放内存
    free(argv);
    return result;
}


#ifdef __cplusplus
}
#endif
#endif

