/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniUtils_FfempegUtils */

#ifndef _Included_jniUtils_FfempegUtils
#define _Included_jniUtils_FfempegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniUtils_FfempegUtils
 * Method:    runFfempeg
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_jniUtils_FfempegUtils_runFfempeg
  (JNIEnv *, jobject);

void progress(char* line);

#ifdef __cplusplus
}
#endif
#endif
